#!/bin/bash
# ============================================================================
# EcoCharge Jump Host (Bastion) Deployment Script
# Variant: SINGLE INTERFACE via Firewall VM
#
# Сервер:  192.168.100.40
# Network: eth0 -> 192.168.100.40/24 (DMZ, єдиний інтерфейс)
# Gateway: 192.168.100.1 (Firewall VM)
#
# Доступ до Internal/OT через static routes via Firewall VM:
#   192.168.20.0/24  (Internal / CSMS)
#   172.16.0.0/24    (OT / Chargers)
#
# ВАЖЛИВО: Після запуску цього скрипту —
#   додайте правила на Firewall VM (інструкції в кінці)
# ============================================================================

set -e

echo "=============================================="
echo "EcoCharge Jump Host Deployment"
echo "Mode: Single Interface via Firewall"
echo "=============================================="

if [ "$EUID" -ne 0 ]; then
    echo "❌ Запустіть з sudo: sudo ./setup.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ============================================================================
# 1. МЕРЕЖА — один інтерфейс, static routes через firewall
# ============================================================================
echo ""
echo "[1/8] Налаштування мережевого інтерфейсу..."

# Знайти перший не-loopback інтерфейс
IF_DMZ=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -1)
IF_DMZ="${IF_DMZ:-eth0}"

echo "   Interface: $IF_DMZ -> 192.168.100.40/24"
echo "   Gateway:   192.168.100.1 (Firewall VM)"
echo "   Static routes via firewall:"
echo "     192.168.20.0/24  (Internal/CSMS)"
echo "     172.16.0.0/24    (OT/Chargers)"

cat > /etc/netplan/01-jump-host.yaml << EOF
# EcoCharge Jump Host — Single Interface via Firewall
# Generated by setup.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IF_DMZ}:
      addresses:
        - 192.168.100.40/24
      routes:
        - to: default
          via: 192.168.100.1
        # Internal та OT — через Firewall VM
        - to: 192.168.20.0/24
          via: 192.168.100.1
          metric: 100
        - to: 172.16.0.0/24
          via: 192.168.100.1
          metric: 200
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
EOF

# Видалити конфліктуючі netplan конфіги
find /etc/netplan/ -name "*.yaml" ! -name "01-jump-host.yaml" -exec rm -f {} \;
netplan apply 2>/dev/null || echo "⚠️  Netplan потребує перезавантаження"
echo "✅ Мережу налаштовано"

# ============================================================================
# 2. ПАКЕТИ
# ============================================================================
echo ""
echo "[2/8] Встановлення необхідних пакетів..."
apt-get update -qq

apt-get install -y -qq \
    openssh-server \
    tcpdump \
    nmap \
    postgresql-client \
    python3 python3-pip python3-venv \
    curl wget netcat-openbsd socat \
    net-tools iproute2 iputils-ping \
    jq vim nano less htop \
    figlet \
    > /dev/null 2>&1

# Node.js + wscat для WebSocket/OCPP взаємодії
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
    apt-get install -y -qq nodejs > /dev/null 2>&1
fi
npm install -g wscat 2>/dev/null || echo "⚠️  wscat не встановлено"
echo "✅ Пакети встановлено"

# ============================================================================
# 3. КОРИСТУВАЧ operator
# ============================================================================
echo ""
echo "[3/8] Створення користувача operator..."

if ! id "operator" &>/dev/null; then
    useradd -m -s /bin/bash -G sudo,adm,tcpdump operator
    echo "operator:Oper4tor_2024!" | chpasswd
fi

mkdir -p /home/operator/.ssh
chmod 700 /home/operator/.ssh

if [ -f "${SCRIPT_DIR}/ssh-keys/id_jumphost" ]; then
    cp "${SCRIPT_DIR}/ssh-keys/id_jumphost.pub" /home/operator/.ssh/authorized_keys
    echo "   Використано ключ з репозиторію"
else
    ssh-keygen -t ed25519 -f /tmp/id_jumphost -N "" -C "operator@jumphost" > /dev/null 2>&1
    cp /tmp/id_jumphost.pub /home/operator/.ssh/authorized_keys
    mkdir -p "${SCRIPT_DIR}/ssh-keys"
    cp /tmp/id_jumphost "${SCRIPT_DIR}/ssh-keys/id_jumphost"
    cp /tmp/id_jumphost.pub "${SCRIPT_DIR}/ssh-keys/id_jumphost.pub"
    rm -f /tmp/id_jumphost /tmp/id_jumphost.pub
    echo "   ⚠️  Новий SSH ключ: ${SCRIPT_DIR}/ssh-keys/id_jumphost"
    echo "   Скопіюйте на Web Server:"
    echo "   scp ${SCRIPT_DIR}/ssh-keys/id_jumphost root@192.168.250.50:/root/.ssh/id_jumphost"
fi

chmod 600 /home/operator/.ssh/authorized_keys
chown -R operator:operator /home/operator/.ssh
echo "✅ Користувача operator створено"

# ============================================================================
# 4. SSH
# ============================================================================
echo ""
echo "[4/8] Налаштування SSH..."

cat > /etc/ssh/sshd_config.d/jumphost.conf << 'EOF'
# EcoCharge Jump Host SSH Configuration
PubkeyAuthentication yes
PasswordAuthentication yes
PermitRootLogin no
# Дозволити тунелі (для SSH pivoting атакуючим)
AllowTcpForwarding yes
GatewayPorts no
PermitTunnel yes
AllowUsers operator
Banner /etc/ssh/banner.txt
LogLevel INFO
EOF

cat > /etc/ssh/banner.txt << 'EOF'
╔══════════════════════════════════════════════════════╗
║        EcoCharge Infrastructure - Jump Host          ║
║  Authorized personnel only. Sessions are monitored.  ║
║  Network: DMZ Management (192.168.100.0/24)          ║
╚══════════════════════════════════════════════════════╝
EOF

systemctl restart sshd
echo "✅ SSH налаштовано"

# ============================================================================
# 5. FLAG #6
# ============================================================================
echo ""
echo "[5/8] Розміщення FLAG #6..."

# MOTD — показує один інтерфейс + роути через firewall
cat > /etc/update-motd.d/99-ecocharge << 'EOF'
#!/bin/bash
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          EcoCharge Jump Host - Connected             ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  Hostname:  jumphost.ecocharge.internal              ║"
echo "║  Role:      Infrastructure Management Bastion        ║"
echo "║                                                      ║"
echo "║  Interface:                                          ║"
echo "║    eth0: 192.168.100.40/24  (Management DMZ)         ║"
echo "║                                                      ║"
echo "║  Routed via firewall (192.168.100.1):                ║"
echo "║    192.168.20.0/24   (Internal / CSMS)               ║"
echo "║    172.16.0.0/24     (OT / Chargers)                 ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
EOF
chmod +x /etc/update-motd.d/99-ecocharge

# Прибрати шумні стандартні MOTD скрипти
for f in /etc/update-motd.d/10-help-text \
         /etc/update-motd.d/50-motd-news \
         /etc/update-motd.d/91-release-upgrade; do
    [ -f "$f" ] && chmod -x "$f"
done

# FLAG у файлі
echo "FLAG{p1v0t_m4st3r_jumb0}" > /home/operator/.flag6.txt
chown operator:operator /home/operator/.flag6.txt
chmod 400 /home/operator/.flag6.txt

# .bashrc — welcome message з реалістичними підказками
cat >> /home/operator/.bashrc << 'EOF'

# EcoCharge Jump Host welcome
echo ""
echo "  Welcome, operator!"
echo "  Accessible networks:"
echo "    DMZ:      192.168.100.0/24 (eth0, direct)"
echo "    Internal: 192.168.20.0/24  (via firewall)"
echo "    OT:       172.16.0.0/24    (via firewall)"
echo ""
echo "  Quick commands:"
echo "    psql -h 192.168.20.20 -U citrine -d citrine"
echo "    wscat -c ws://192.168.20.20:8092/CP001"
echo "    tcpdump -i eth0 host 192.168.20.20 and port 8092"
echo "    ./scripts/check-stations.sh"
echo ""
EOF

echo "✅ FLAG #6 розміщено"

# ============================================================================
# 6. ДОПОМІЖНІ СКРИПТИ
# ============================================================================
echo ""
echo "[6/8] Створення допоміжних скриптів..."

mkdir -p /home/operator/scripts

# check-stations.sh — без змін, IP адреси ті самі
cat > /home/operator/scripts/check-stations.sh << 'EOF'
#!/bin/bash
# EcoCharge - Station Health Check
echo "=== EcoCharge Station Health Check ==="
echo "Date: $(date)"
echo ""
echo "[Checking CSMS Core...]"
curl -sf http://192.168.20.20:8080/docs > /dev/null 2>&1 \
    && echo "  ✅ CSMS API: OK" || echo "  ❌ CSMS API: UNREACHABLE"
echo ""
echo "[Checking Chargers...]"
ping -c 1 -W 2 172.16.0.40 > /dev/null 2>&1 \
    && echo "  ✅ CP001 (172.16.0.40): REACHABLE" \
    || echo "  ❌ CP001 (172.16.0.40): UNREACHABLE"
ping -c 1 -W 2 172.16.0.60 > /dev/null 2>&1 \
    && echo "  ✅ CP002 (172.16.0.60): REACHABLE" \
    || echo "  ❌ CP002 (172.16.0.60): UNREACHABLE"
echo ""
echo "[Checking Grafana...]"
curl -sf http://192.168.100.30:3000/api/health > /dev/null 2>&1 \
    && echo "  ✅ Grafana: OK" || echo "  ❌ Grafana: UNREACHABLE"
echo ""
echo "[Checking API Gateway...]"
curl -sf http://192.168.100.20:3000/api/v1/health > /dev/null 2>&1 \
    && echo "  ✅ API Gateway: OK" || echo "  ❌ API Gateway: UNREACHABLE"
echo ""
echo "=== Check Complete ==="
EOF

# ocpp-debug.sh — ЗМІНА: eth2 -> eth0 + wscat як основний метод
cat > /home/operator/scripts/ocpp-debug.sh << 'EOF'
#!/bin/bash
# EcoCharge - OCPP Debug Tool
# Single-interface variant: traffic captured on eth0
#
# OCPP 1.6 (CP001, port 8092) — NOT encrypted
# OCPP 2.0.1 (CP002, port 8081) — Security Profile 1

echo "=== OCPP Debug Tool ==="
echo ""
echo "Available methods:"
echo ""
echo "1. Passive capture (traffic routed through eth0):"
echo "   sudo tcpdump -i eth0 -A 'host 192.168.20.20 and (port 8092 or port 8081)'"
echo ""
echo "2. Active OCPP 1.6 interaction (CP001):"
echo "   wscat -c ws://192.168.20.20:8092/CP001"
echo ""
echo "3. Send RemoteStopTransaction:"
echo "   wscat -c ws://192.168.20.20:8092/CP001"
echo "   > [2,\"stop-001\",\"RemoteStopTransaction\",{\"transactionId\":1}]"
echo ""

if [ "$1" = "capture" ]; then
    echo "Starting passive capture on eth0..."
    tcpdump -i eth0 -A \
        "host 192.168.20.20 and (port 8092 or port 8081 or port 8080)" \
        2>/dev/null || echo "Error: run as sudo"
fi
EOF

# db-maintenance.sh — без змін
cat > /home/operator/scripts/db-maintenance.sh << 'EOF'
#!/bin/bash
# EcoCharge - Database Maintenance
# Connection: citrine:citrine@192.168.20.20:5432/citrine
echo "=== Database Maintenance ==="
echo "Connecting to CitrineOS PostgreSQL..."
echo ""
PGPASSWORD=citrine psql \
    -h 192.168.20.20 -U citrine -d citrine \
    -c "SELECT 'Connected' as status, version();" \
    2>/dev/null || echo "❌ Cannot connect to database"
echo ""
echo "=== Maintenance Complete ==="
EOF

chmod +x /home/operator/scripts/*.sh
chown -R operator:operator /home/operator/scripts

# SSH config — без змін
cat > /home/operator/.ssh/config << 'EOF'
# EcoCharge Infrastructure SSH Config
Host csms
    HostName 192.168.20.20
    User admin
    Port 22
Host grafana
    HostName 192.168.100.30
    User admin
    Port 22
Host api-gw
    HostName 192.168.100.20
    User admin
    Port 22
EOF
chmod 600 /home/operator/.ssh/config
chown operator:operator /home/operator/.ssh/config

# .bash_history — ЗМІНА: eth2 -> eth0 у tcpdump
cat > /home/operator/.bash_history << 'EOF'
ping 192.168.20.20
psql -h 192.168.20.20 -U citrine -d citrine -c "SELECT id FROM \"ChargingStation\";"
curl http://192.168.100.30:3000/api/health
./scripts/check-stations.sh
tcpdump -i eth0 -A host 192.168.20.20 and port 8092
wscat -c ws://192.168.20.20:8092/CP001
ssh -L 3000:192.168.100.30:3000 operator@localhost
nmap -sV 192.168.20.20 -p 5432,8080,8081,8092
EOF
chown operator:operator /home/operator/.bash_history

echo "✅ Допоміжні скрипти створено"

# ============================================================================
# 7. IPTABLES на Jump Host
# ============================================================================
echo ""
echo "[7/8] Налаштування iptables на Jump Host..."

iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP

iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -s 192.168.100.0/24 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -s 192.168.250.0/24 -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
# Forwarding для SSH tunneling
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -s 192.168.100.0/24 -j ACCEPT

# IP forwarding НЕ потрібен на Jump Host —
# маршрутизацію між зонами виконує Firewall VM
echo 0 > /proc/sys/net/ipv4/ip_forward

mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
apt-get install -y -qq iptables-persistent > /dev/null 2>&1 || true
echo "✅ iptables налаштовано"

# ============================================================================
# 8. HOSTNAME & /ETC/HOSTS
# ============================================================================
echo ""
echo "[8/8] Фінальні налаштування..."

hostnamectl set-hostname jumphost.ecocharge.internal 2>/dev/null || \
    echo "jumphost.ecocharge.internal" > /etc/hostname

cat >> /etc/hosts << 'EOF'

# EcoCharge Infrastructure
192.168.100.20  api-gw api-gateway.ecocharge.internal
192.168.100.30  grafana grafana.ecocharge.internal
192.168.100.40  jumphost jumphost.ecocharge.internal
192.168.20.20   csms citrine-db csms.ecocharge.internal
172.16.0.40     cp001 cp001.ecocharge.internal
172.16.0.60     cp002 cp002.ecocharge.internal
EOF

# tcpdump без sudo для operator
usermod -aG tcpdump operator 2>/dev/null || true
setcap cap_net_raw+ep /usr/bin/tcpdump 2>/dev/null || true

echo "✅ Систему налаштовано"

# ============================================================================
# ЗАВЕРШЕННЯ
# ============================================================================
echo ""
echo "=============================================="
echo "✅ JUMP HOST РОЗГОРНУТО УСПІШНО!"
echo "=============================================="
echo ""
echo "Network:"
echo "  eth0: 192.168.100.40/24 (DMZ)"
echo "  → 192.168.20.0/24  via 192.168.100.1 (Firewall)"
echo "  → 172.16.0.0/24    via 192.168.100.1 (Firewall)"
echo ""
echo "Access:"
echo "  SSH: operator@192.168.100.40"
echo "  Key: ${SCRIPT_DIR}/ssh-keys/id_jumphost"
echo ""
echo "Copy key to Web Server:"
echo "  scp ${SCRIPT_DIR}/ssh-keys/id_jumphost \\"
echo "      root@192.168.250.50:/root/.ssh/id_jumphost"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  REQUIRED: Add rules on your Firewall VM"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  # Jump Host <-> Internal (CSMS)"
echo "  iptables -I FORWARD 1 \\"
echo "      -s 192.168.100.40 -d 192.168.20.0/24 -j ACCEPT"
echo "  iptables -I FORWARD 2 \\"
echo "      -s 192.168.20.0/24 -d 192.168.100.40 -j ACCEPT"
echo ""
echo "  # Jump Host <-> OT (Chargers)"
echo "  iptables -I FORWARD 3 \\"
echo "      -s 192.168.100.40 -d 172.16.0.0/24 -j ACCEPT"
echo "  iptables -I FORWARD 4 \\"
echo "      -s 172.16.0.0/24 -d 192.168.100.40 -j ACCEPT"
echo ""
echo "  # Save"
echo "  iptables-save > /etc/iptables/rules.v4"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test after firewall rules:"
echo "  ping 192.168.20.20   # CSMS"
echo "  ping 172.16.0.40     # CP001"
echo ""
