#!/bin/bash
# ============================================================================
# EcoCharge Jump Host (Bastion) Deployment Script
# Сервер: 192.168.100.40
# Multi-homed: DMZ (.100.40), Internal (.20.40), OT (172.16.0.10)
# ============================================================================

set -e

echo "=============================================="
echo "EcoCharge Jump Host Deployment"
echo "=============================================="

# --- Перевірка root ---
if [ "$EUID" -ne 0 ]; then
    echo "❌ Запустіть з sudo: sudo ./setup.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ============================================================================
# 1. МЕРЕЖА
# ============================================================================
echo ""
echo "[1/8] Налаштування мережевих інтерфейсів..."

# Визначити інтерфейси (Proxmox зазвичай дає ens18, ens19, ens20 або eth0, eth1, eth2)
IFACES=($(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -3))

if [ ${#IFACES[@]} -lt 3 ]; then
    echo "⚠️  Знайдено лише ${#IFACES[@]} інтерфейс(и): ${IFACES[*]}"
    echo "   Jump Host потребує 3 інтерфейси (DMZ, Internal, OT)."
    echo "   Додайте мережеві адаптери в Proxmox і перезапустіть."
    echo ""
    echo "   Продовжую з наявними інтерфейсами..."
fi

# Отримати назви
IF_DMZ="${IFACES[0]:-eth0}"
IF_INTERNAL="${IFACES[1]:-eth1}"
IF_OT="${IFACES[2]:-eth2}"

echo "   DMZ interface:      $IF_DMZ -> 192.168.100.40/24"
echo "   Internal interface:  $IF_INTERNAL -> 192.168.20.40/24"
echo "   OT interface:        $IF_OT -> 172.16.0.10/24"

# Створити Netplan конфігурацію
cat > /etc/netplan/01-jump-host.yaml << EOF
# EcoCharge Jump Host Network Configuration
# Generated by setup.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IF_DMZ}:
      addresses:
        - 192.168.100.40/24
      routes:
        - to: default
          via: 192.168.100.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
    ${IF_INTERNAL}:
      addresses:
        - 192.168.20.40/24
      routes:
        - to: 192.168.20.0/24
          via: 192.168.20.40
          metric: 100
    ${IF_OT}:
      addresses:
        - 172.16.0.10/24
      routes:
        - to: 172.16.0.0/24
          via: 172.16.0.10
          metric: 200
EOF

# Видалити інші netplan конфіги, щоб уникнути конфліктів
find /etc/netplan/ -name "*.yaml" ! -name "01-jump-host.yaml" -exec rm -f {} \;

netplan apply 2>/dev/null || echo "⚠️  Netplan apply потребує перезавантаження"
echo "✅ Мережу налаштовано"

# ============================================================================
# 2. ПАКЕТИ
# ============================================================================
echo ""
echo "[2/8] Встановлення необхідних пакетів..."
apt-get update -qq

apt-get install -y -qq \
    openssh-server \
    tcpdump \
    nmap \
    postgresql-client \
    python3 python3-pip python3-venv \
    curl wget netcat-openbsd socat \
    net-tools iproute2 iputils-ping \
    jq vim nano less htop \
    figlet \
    > /dev/null 2>&1

# wscat для WebSocket (OCPP interaction)
npm install -g wscat 2>/dev/null || {
    # Встановити Node.js якщо немає
    if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
        apt-get install -y -qq nodejs > /dev/null 2>&1
    fi
    npm install -g wscat 2>/dev/null || echo "⚠️  wscat не встановлено (не критично)"
}

echo "✅ Пакети встановлено"

# ============================================================================
# 3. КОРИСТУВАЧ operator
# ============================================================================
echo ""
echo "[3/8] Створення користувача operator..."

# Створити користувача
if ! id "operator" &>/dev/null; then
    useradd -m -s /bin/bash -G sudo,adm,tcpdump operator
    echo "operator:Oper4tor_2024!" | chpasswd
fi

# SSH директорія
mkdir -p /home/operator/.ssh
chmod 700 /home/operator/.ssh

# Генерація SSH ключа (цей же ключ буде розміщено на Web Server)
if [ -f "${SCRIPT_DIR}/ssh-keys/id_jumphost" ]; then
    # Використати ключ з репозиторію
    cp "${SCRIPT_DIR}/ssh-keys/id_jumphost.pub" /home/operator/.ssh/authorized_keys
    echo "   Використано ключ з репозиторію"
else
    # Генерація нового ключа
    ssh-keygen -t ed25519 -f /tmp/id_jumphost -N "" -C "operator@jumphost" > /dev/null 2>&1
    cp /tmp/id_jumphost.pub /home/operator/.ssh/authorized_keys
    
    # Зберегти приватний ключ для копіювання на Web Server
    mkdir -p "${SCRIPT_DIR}/ssh-keys"
    cp /tmp/id_jumphost "${SCRIPT_DIR}/ssh-keys/id_jumphost"
    cp /tmp/id_jumphost.pub "${SCRIPT_DIR}/ssh-keys/id_jumphost.pub"
    rm -f /tmp/id_jumphost /tmp/id_jumphost.pub
    
    echo "   ⚠️  НОВИЙ SSH ключ згенеровано!"
    echo "   Приватний ключ збережено: ${SCRIPT_DIR}/ssh-keys/id_jumphost"
    echo "   СКОПІЮЙТЕ його на Web Server (192.168.250.50) в /root/.ssh/id_jumphost"
fi

chmod 600 /home/operator/.ssh/authorized_keys
chown -R operator:operator /home/operator/.ssh

echo "✅ Користувач operator створено"

# ============================================================================
# 4. SSH КОНФІГУРАЦІЯ
# ============================================================================
echo ""
echo "[4/8] Налаштування SSH..."

cat > /etc/ssh/sshd_config.d/jumphost.conf << 'EOF'
# EcoCharge Jump Host SSH Configuration

# Дозволити автентифікацію по ключу
PubkeyAuthentication yes

# Дозволити автентифікацію по паролю (для CTF — password fallback)
PasswordAuthentication yes

# Заборонити root login по SSH
PermitRootLogin no

# Дозволити тунелі (для SSH pivoting атакуючим)
AllowTcpForwarding yes
GatewayPorts no
PermitTunnel yes

# Дозволити тільки operator
AllowUsers operator

# Banner
Banner /etc/ssh/banner.txt

# Logging
LogLevel INFO
EOF

# SSH Banner
cat > /etc/ssh/banner.txt << 'EOF'
╔══════════════════════════════════════════════════════╗
║        EcoCharge Infrastructure - Jump Host          ║
║                                                      ║
║  Authorized personnel only.                          ║
║  All sessions are monitored and logged.              ║
║                                                      ║
║  Network: DMZ Management (192.168.100.0/24)          ║
╚══════════════════════════════════════════════════════╝
EOF

systemctl restart sshd
echo "✅ SSH налаштовано"

# ============================================================================
# 5. FLAG #6
# ============================================================================
echo ""
echo "[5/8] Розміщення FLAG #6..."

# MOTD з FLAG
cat > /etc/update-motd.d/99-ecocharge << 'MOTDEOF'
#!/bin/bash
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          EcoCharge Jump Host - Connected             ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  Hostname:  jumphost.ecocharge.internal              ║"
echo "║  Role:      Infrastructure Management Bastion        ║"
echo "║                                                      ║"
echo "║  Networks:                                           ║"
echo "║    eth0: 192.168.100.40/24  (Management DMZ)         ║"
echo "║    eth1: 192.168.20.40/24   (Internal/CSMS)          ║"
echo "║    eth2: 172.16.0.10/24     (OT/Chargers)            ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
MOTDEOF
chmod +x /etc/update-motd.d/99-ecocharge

# Видалити стандартні MOTD скрипти, щоб не засмічували вивід
for f in /etc/update-motd.d/10-help-text /etc/update-motd.d/50-motd-news /etc/update-motd.d/91-release-upgrade; do
    [ -f "$f" ] && chmod -x "$f"
done

# FLAG #6 у файлі (альтернативне місце)
echo "FLAG{p1v0t_m4st3r_jumb0}" > /home/operator/.flag6.txt
chown operator:operator /home/operator/.flag6.txt
chmod 400 /home/operator/.flag6.txt

# Також у .bashrc як привітання
cat >> /home/operator/.bashrc << 'BASHRCEOF'

# EcoCharge Jump Host
echo ""
echo "  Welcome, operator!"
echo "  Jump Host ready. Connected networks:"
echo "    DMZ:      192.168.100.0/24 (eth0)"
echo "    Internal: 192.168.20.0/24  (eth1)"
echo "    OT:       172.16.0.0/24    (eth2)"
echo ""
echo "  Useful commands:"
echo "    nmap -sV 192.168.20.20         # Scan CSMS"
echo "    psql -h 192.168.20.20 -U citrine -d citrine  # Database"
echo "    tcpdump -i eth2 port 8092      # OCPP traffic"
echo ""

BASHRCEOF

echo "✅ FLAG #6 розміщено"

# ============================================================================
# 6. ПОМІЧНІ СКРИПТИ (для реалістичності)
# ============================================================================
echo ""
echo "[6/8] Створення допоміжних скриптів..."

mkdir -p /home/operator/scripts

# Скрипт моніторингу (realism)
cat > /home/operator/scripts/check-stations.sh << 'STATIONSEOF'
#!/bin/bash
# EcoCharge - Station Health Check Script
# Used by operator for daily checks

echo "=== EcoCharge Station Health Check ==="
echo "Date: $(date)"
echo ""

echo "[Checking CSMS Core...]"
curl -sf http://192.168.20.20:8080/docs > /dev/null 2>&1 && echo "  ✅ CSMS API: OK" || echo "  ❌ CSMS API: UNREACHABLE"

echo ""
echo "[Checking Charger Connectivity...]"
ping -c 1 -W 2 172.16.0.40 > /dev/null 2>&1 && echo "  ✅ CP001 (172.16.0.40): REACHABLE" || echo "  ❌ CP001 (172.16.0.40): UNREACHABLE"
ping -c 1 -W 2 172.16.0.60 > /dev/null 2>&1 && echo "  ✅ CP002 (172.16.0.60): REACHABLE" || echo "  ❌ CP002 (172.16.0.60): UNREACHABLE"

echo ""
echo "[Checking Grafana...]"
curl -sf http://192.168.100.30:3000/api/health > /dev/null 2>&1 && echo "  ✅ Grafana: OK" || echo "  ❌ Grafana: UNREACHABLE"

echo ""
echo "[Checking API Gateway...]"
curl -sf http://192.168.100.20:8080/api/v1/health > /dev/null 2>&1 && echo "  ✅ API Gateway: OK" || echo "  ❌ API Gateway: UNREACHABLE"

echo ""
echo "=== Check Complete ==="
STATIONSEOF

# Скрипт OCPP sniff (підказка для атакуючого)
cat > /home/operator/scripts/ocpp-debug.sh << 'OCPPEOF'
#!/bin/bash
# EcoCharge - OCPP Debug Tool
# NOTE: OCPP 1.6 on port 8092 is UNENCRYPTED (ws://)
# OCPP 2.0.1 on port 8081 uses Security Profile 1

echo "=== OCPP Debug Capture ==="
echo "Capturing OCPP 1.6 traffic on OT network (eth2)..."
echo "Press Ctrl+C to stop"
echo ""
echo "NOTE: OCPP 1.6 traffic is NOT encrypted!"
echo "      Charger CP001 -> CSMS on ws://192.168.20.20:8092"
echo ""

# Capture WebSocket traffic on OCPP 1.6 port
tcpdump -i eth2 -A port 8092 2>/dev/null || echo "Error: need to run as: sudo ./ocpp-debug.sh"
OCPPEOF

# Скрипт для підключення до БД (ще одна підказка)
cat > /home/operator/scripts/db-maintenance.sh << 'DBEOF'
#!/bin/bash
# EcoCharge - Database Maintenance Script
# Connection: citrine:citrine@192.168.20.20:5432/citrine
# Run weekly for cleanup

echo "=== Database Maintenance ==="
echo "Connecting to CitrineOS PostgreSQL..."
echo ""

PGPASSWORD=citrine psql -h 192.168.20.20 -U citrine -d citrine -c "
SELECT 
    'ChargingStations' as table_name, COUNT(*) as rows FROM \"ChargingStations\"
UNION ALL
SELECT 
    'Transactions', COUNT(*) FROM \"Transactions\"
UNION ALL
SELECT 
    'OCPPMessages', COUNT(*) FROM \"OCPPMessages\"
UNION ALL
SELECT 
    'Authorizations', COUNT(*) FROM \"Authorizations\";
" 2>/dev/null || echo "❌ Cannot connect to database"

echo ""
echo "=== Maintenance Complete ==="
DBEOF

chmod +x /home/operator/scripts/*.sh
chown -R operator:operator /home/operator/scripts

# SSH config з підказками хостів
cat > /home/operator/.ssh/config << 'SSHCEOF'
# EcoCharge Infrastructure SSH Config

Host csms
    HostName 192.168.20.20
    User admin
    Port 22

Host grafana
    HostName 192.168.100.30
    User admin
    Port 22

Host api-gw
    HostName 192.168.100.20
    User admin
    Port 22
SSHCEOF
chown operator:operator /home/operator/.ssh/config
chmod 600 /home/operator/.ssh/config

# .bash_history з підказками (pre-populated)
cat > /home/operator/.bash_history << 'HISTEOF'
ping 192.168.20.20
psql -h 192.168.20.20 -U citrine -d citrine -c "SELECT id, \"isOnline\" FROM \"ChargingStations\";"
curl http://192.168.100.30:3000/api/health
./scripts/check-stations.sh
tcpdump -i eth2 -c 10 port 8092
ssh -L 3000:192.168.100.30:3000 operator@localhost
nmap -sV 192.168.20.20 -p 5432,8080,8081,8092
curl http://192.168.100.20:8080/debug/config
HISTEOF
chown operator:operator /home/operator/.bash_history

echo "✅ Допоміжні скрипти створено"

# ============================================================================
# 7. IPTABLES
# ============================================================================
echo ""
echo "[7/8] Налаштування iptables..."

# Flush existing rules
iptables -F INPUT
iptables -F OUTPUT
iptables -F FORWARD

# Default policies
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP

# Loopback
iptables -A INPUT -i lo -j ACCEPT

# Established connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# SSH з DMZ (для доступу оператора / атакуючого)
iptables -A INPUT -p tcp --dport 22 -s 192.168.100.0/24 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -s 192.168.250.0/24 -j ACCEPT

# ICMP (ping) з усіх мереж
iptables -A INPUT -p icmp -j ACCEPT

# Дозволити forwarding (для SSH tunneling атакуючим)
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -s 192.168.100.0/24 -j ACCEPT
iptables -A FORWARD -s 192.168.250.0/24 -j ACCEPT

# Enable IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf || echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sysctl -p > /dev/null 2>&1

# Зберегти правила
if command -v iptables-save &> /dev/null; then
    mkdir -p /etc/iptables
    iptables-save > /etc/iptables/rules.v4
fi

# Persist iptables across reboots
apt-get install -y -qq iptables-persistent > /dev/null 2>&1 || true

echo "✅ iptables налаштовано"

# ============================================================================
# 8. HOSTNAME & SYSTEM
# ============================================================================
echo ""
echo "[8/8] Фінальні налаштування..."

# Hostname
hostnamectl set-hostname jumphost.ecocharge.internal 2>/dev/null || \
    echo "jumphost.ecocharge.internal" > /etc/hostname

# /etc/hosts з внутрішніми ресурсами
cat >> /etc/hosts << 'HOSTSEOF'

# EcoCharge Infrastructure
192.168.100.20  api-gateway.ecocharge.internal api-gw
192.168.100.30  grafana.ecocharge.internal grafana
192.168.100.40  jumphost.ecocharge.internal jumphost
192.168.20.20   csms.ecocharge.internal csms citrine-db
172.16.0.40     cp001.ecocharge.internal cp001
172.16.0.60     cp002.ecocharge.internal cp002
HOSTSEOF

# tcpdump group permissions (щоб operator міг запускати без sudo)
usermod -aG tcpdump operator 2>/dev/null || true
setcap cap_net_raw+ep /usr/bin/tcpdump 2>/dev/null || \
    chmod u+s /usr/sbin/tcpdump 2>/dev/null || true

echo "✅ Систему налаштовано"

# ============================================================================
# ЗАВЕРШЕННЯ
# ============================================================================
echo ""
echo "=============================================="
echo "✅ JUMP HOST РОЗГОРНУТО УСПІШНО!"
echo "=============================================="
echo ""
echo "Мережеві інтерфейси:"
echo "  • eth0 (DMZ):      192.168.100.40/24"
echo "  • eth1 (Internal):  192.168.20.40/24"
echo "  • eth2 (OT):        172.16.0.10/24"
echo ""
echo "Доступ:"
echo "  • SSH: operator@192.168.100.40"
echo "  • Пароль: Oper4tor_2024!"
echo "  • SSH ключ: ssh-keys/id_jumphost"
echo ""
echo "CTF Info:"
echo "  • FLAG #6: /home/operator/.flag6.txt"
echo "  • FLAG #6 також відображається при SSH логіні"
echo ""
echo "⚠️  ВАЖЛИВО:"
echo "  Скопіюйте приватний ключ на Web Server:"
echo "    scp ${SCRIPT_DIR}/ssh-keys/id_jumphost root@192.168.250.50:/root/.ssh/id_jumphost"
echo "    ssh root@192.168.250.50 'chmod 600 /root/.ssh/id_jumphost'"
echo ""
echo "Перевірка підключень:"
echo "  ssh -i ssh-keys/id_jumphost operator@192.168.100.40"
echo ""
